### ISSUE TITLE
Licensing and legal disclaimers

### ISSUE THREAD

**Issue by ptaranat** [matthewfee/OSECharacterGenerator#43]
Lets bump this to the top, got a request from Necrotic Gnome:
![brave_L9wiqg0G7P](https://user-images.githubusercontent.com/15150173/215439810-420bc528-891a-4f5c-b3e8-5f02c0be3fa5.png)

Previous PR changed the wording on the front page about the permission. Let's change it back and add details for the respective authors.

- We could change "Additional classes included with the permission of Necrotic Gnome & James Maliszewski." to `"Permission to include details of the additional classes from Advanced Fantasy and the Carcass Crawler zine granted by Necrotic Gnome and James Maliszewski."`

- Let's also add links to https://necroticgnome.com/ and https://grognardia.blogspot.com/ when clicking on their names.

- We should revise the footer and use some legalese. Perhaps something like:

> OSE Character Generator is an independent open source project by EvilTables & contributors and not affiliated with Necrotic Gnome.
  - EvilTables could link to https://eviltables.dev/ and contributors could link to the GitHub contributors page. Feel free to remove my credit for space.
- We also need to add the OSE 3rd party license required legal text:
> Old-School Essentials is a trademark of Necrotic Gnome. The trademark and Old-School Essentials logo are used with permission of Necrotic Gnome, under license

- We need to grab some sort of OGL compatible license. It depends how much of this content is OGL. I think some spell names might fall under that but not sure. We do use a bunch of text from the Player Character section for class descriptions, however. This is prohibited by the 3rd party OSE license.
- I don't know German so gonna need some help with i18n lol

**Comment by matthewfee** [comment]
Yes, these changes make sense. If you want to use Google Translate or DeepL for translations that is no problem, it doesn't need to be perfect :)

**Comment by ptaranat** [comment]
One thing I'm waiting to hear back from Necrotic Gnome about is whether we are required to change the title of the product from "OSE Character Generator" to "Old-School Character Generator". Since this is not an official or endorsed product, we cannot use OSE as part of the title, but we can for subtitles.
